const $=id=>document.getElementById(id), E=new TextEncoder();
async function hash(s){let h=await crypto.subtle.digest("SHA-256",E.encode(s));return[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,"0")).join("")}
let saved=localStorage.getItem("mimmir_founder_hash");
function gateMode(){saved=localStorage.getItem("mimmir_founder_hash");$("gateBtn").textContent=saved?"Unlock Founder Console":"Initialize Founder Key";$("gateText").textContent=saved?"Founder authentication required.":"Create the Founder Key for this device. It is never stored as plain text."}gateMode();
$("gateBtn").onclick=async()=>{let p=$("pw").value;if(p.length<6)return $("msg").textContent="Use at least 6 characters.";let h=await hash(p);if(!saved){localStorage.setItem("mimmir_founder_hash",h);saved=h}else if(h!==saved)return $("msg").textContent="Access denied.";$("gate").hidden=true;$("console").hidden=false;load()};
function cfg(){return{name:$("name").value,founder:$("founder").value,persona:$("persona").value,admin:$("admin").checked,approval:$("approval").checked,memory:$("memory").checked,device:$("device").checked,cloud:$("cloud").checked,endpoint:$("endpoint").value || "https://mimmir-brain.kdking2502.workers.dev",version:"0.2.0-founder"}}
function load(){let c=JSON.parse(localStorage.getItem("mimmir_config")||"{}");for(let k of["name","founder","persona","endpoint"])if(c[k]!=null)$(k).value=c[k];for(let k of["admin","approval","memory","device","cloud"])if(c[k]!=null)$(k).checked=!!c[k]}
function save(){localStorage.setItem("mimmir_config",JSON.stringify(cfg()))}$("save").onclick=save;$("saveAuth").onclick=save;
function add(role,text){let d=document.createElement("div");d.className=role;let b=document.createElement("b"),p=document.createElement("p");b.textContent=role==="u"?($("founder").value||"Founder"):($("name").value||"Mimmir");p.textContent=text;d.append(b,p);$("chat").append(d);$("chat").scrollTop=$("chat").scrollHeight}
$("send").onclick=async()=>{let t=$("input").value.trim();if(!t)return;add("u",t);$("input").value="";let c=cfg();if(!c.cloud||!c.endpoint)return add("m","My private Brain is not connected yet. I received your message locally, but I cannot generate an AI response until the secure Brain endpoint is online.");try{let r=await fetch(c.endpoint.replace(/\/$/,"")+"/v1/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:t,founder:c.founder,assistant:c.name,persona:c.persona,requireApproval:c.approval,memoryAllowed:c.memory})});if(!r.ok)throw 0;let x=await r.json();add("m",x.reply||x.message||"Brain responded without a message.")}catch{add("m","I could not reach the private Brain. Check the endpoint and connection settings.")}};
$("input").onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();$("send").click()}};
$("test").onclick=async()=>{let u=$("endpoint").value.trim();if(!u)return $("state").textContent="NO ENDPOINT";$("state").textContent="TESTING…";try{let r=await fetch(u);$("state").textContent=r.ok?"REACHABLE":"HTTP "+r.status}catch{$("state").textContent="UNREACHABLE"}};
$("lock").onclick=()=>{$("console").hidden=true;$("gate").hidden=false;$("pw").value=""};
$("reset").onclick=()=>{if(prompt("Type RESET MIMMIR to erase local settings.")==="RESET MIMMIR"){localStorage.clear();location.reload()}};
if("serviceWorker"in navigator)navigator.serviceWorker.register("./service-worker.js");
